Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.33.103"
  config.vm.hostname = "example3.local"

  # Manage host
  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  else
    puts '[WARNING] Host manager plugin is not installed! Please run `vagrant plugin install vagrant-hostmanager`'
  end
 
  # Files for puppet
  config.vm.synced_folder "./puppet-files", "/etc/puppet/files"

  # Ensure we have the mysql and apache puppet modules on the vm
  # https_proxy=$http_proxy is added due to bug in puppet, see https://tickets.puppetlabs.com/browse/FORGE-70
  config.vm.provision "shell", inline: 'mkdir -p /etc/puppet/modules; (puppet module list | grep puppetlabs-mysql) || https_proxy=$http_proxy puppet module install puppetlabs/mysql'
  config.vm.provision "shell", inline: 'mkdir -p /etc/puppet/modules; (puppet module list | grep puppetlabs-apache) || https_proxy=$http_proxy puppet module install puppetlabs/apache'

  # Provision using puppet
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
    puppet.options = ['--fileserverconfig=/vagrant/fileserver.conf']
  end

  config.vm.post_up_message = "Machine ready, browse to http://example3.local/ in your browser to see wordpress."
end
